create table color_chart_user_details (
    id varchar(255) not null,
    email varchar(255),
    gender varchar(255),
    last_visit timestamp,
    locale varchar(255),
    name varchar(255),
    userpic varchar(255),
    primary key (id)
);

create table paint (
    id int8 generated by default as identity,
    color int8,
    company_color_number varchar(255),
    granulation varchar(255),
    lightfastness varchar(255),
    name varchar(255) not null,
    opacity varchar(255),
    serial_number int8,
    picture_id int8,
    producer_id int8,
    staining varchar(255),
    primary key (id)
);

create table paint_pigments (
    paint_id int8 not null,
    pigment_id int8 not null,
    primary key (paint_id, pigment_id)
);

create table picture (
    id int8 generated by default as identity,
    name varchar(255),
    picture bytea,
    primary key (id)
);

create table pigment (
    id int8 generated by default as identity,
    pigment_index varchar(255) not null,
    primary key (id)
)

create table producer (
    id int8 generated by default as identity,
    country varchar(255) not null,
    producer_name varchar(255) not null,
    primary key (id)
);

alter table if exists paint
    add constraint UK_65gcwhnv42usjg27p31u3vc6 unique (name)

alter table if exists pigment
    add constraint UK_6x3n5gddssw8dgrb3l5f1xxhv unique (pigment_index)

alter table if exists producer
    add constraint UK_4a9s7018djdmoxc85ddgu4ra9 unique (producer_name)

alter table if exists paint
    add constraint FK4rcxgivt4pg9iw09ec393pqfs foreign key (picture_id) references picture

alter table if exists paint
    add constraint FKifvvebj3scby9i84p2973c4y2 foreign key (producer_id) references producer

alter table if exists paint_pigments
    add constraint FKt0aqnb1okso7guaus3e2t0bpp foreign key (pigment_id) references pigment

alter table if exists paint_pigments
    add constraint FK4isnrl0p6hujkerjqs8v5nkp4 foreign key (paint_id) references paint
