create table color_chart_user_details (
    id varchar(255) not null,
    email varchar(255),
    gender varchar(255),
    last_visit timestamp,
    locale varchar(255),
    name varchar(255),
    userpic varchar(255),
    primary key (id)
);

create table paint (
    id int8 generated by default as identity,
    color int8,
    company_color_number varchar(255),
    granulation varchar(255),
    lightfastness varchar(255),
    name varchar(255) not null,
    opacity varchar(255),
    serial_number int8,
    picture_id int8,
    producer_id int8,
    staining varchar(255),
    primary key (id)
);

create table paint_pigments (
    paint_id int8 not null,
    pigment_id int8 not null,
    primary key (paint_id, pigment_id)
);

create table picture (
    id int8 generated by default as identity,
    name varchar(255),
    picture bytea,
    primary key (id)
);

create table pigment (
    id int8 generated by default as identity,
    pigment_index varchar(255) not null,
    primary key (id)
);

create table producer (
    id int8 generated by default as identity,
    country varchar(255) not null,
    producer_name varchar(255) not null,
    primary key (id)
);

alter table if exists paint
    add constraint UK_name unique (name);

alter table if exists pigment
    add constraint UK_pigment_index unique (pigment_index);

alter table if exists producer
    add constraint UK_producer_name unique (producer_name);

alter table if exists paint
    add constraint FK_Paint_Picture foreign key (picture_id) references picture;

alter table if exists paint
    add constraint FK_Paint_Producer foreign key (producer_id) references producer;

alter table if exists paint_pigments
    add constraint FK_Paint_pigments_Pigment foreign key (pigment_id) references pigment;

alter table if exists paint_pigments
    add constraint FK_Paint_pigments_Paint foreign key (paint_id) references paint;
